#!/bin/sh -e

. /lib/lsb/init-functions

_PROJECT_NAME=network-slicing-engine
_CONFIG_FILE=/etc/openbaton/network-slicing-engine.properties
_DEFAULT_CONFIG_FILE=etc/network-slicing-engine.properties
_PROJECT_EXE_FOLDER=/usr/bin
_PROJECT_LOGS_FOLDER=/var/log/openbaton

TMPFOLDER=$(mktemp -d)

_USER="$(id -un 2>/dev/null || true)"

checkBinary () {
    if command -v $1 >/dev/null 2>&1 ; then
        log_success_msg "Checking for '$1'"
        return 0
    else
        log_failure_msg "Checking for '$1'"
        return 1
    fi
}

_ex='sh -c'
if [ "${_USER}" != 'root' ]; then
    if checkBinary sudo; then
        _ex='sudo -E sh -c'
    elif checkBinary su; then
        _ex='su -c'
    fi
fi

ulimit -S -n 4096


# Set the installation mode (interactive or not interactive)
INTERACTIVE=true
RESULT=$(env | grep DEBIAN_FRONTEND=noninteractive | wc -l)
if [ ${RESULT} -ne 0 ]; then
    INTERACTIVE=false
fi

##########################################
#### Configure project ####
##########################################

createLogsFolder () {
    if [ ! -d "${_PROJECT_LOGS_FOLDER}" ]; then
        $_ex 'mkdir -p '"$_PROJECT_LOGS_FOLDER"
        log_success_msg "Created log folder \"${_PROJECT_LOGS_FOLDER}\""
    fi
    $_ex 'chown -R '"$_USER $_PROJECT_LOGS_FOLDER"
    log_success_msg "Configured permissions of log folder \"${_PROJECT_LOGS_FOLDER}\""
}

configure () {
    log_success_msg "Giving ${_PROJECT_NAME} execution permissions ..."
    $_ex "chmod a+x ${_PROJECT_EXE_FOLDER}/${_PROJECT_NAME}"

    createLogsFolder

    log_success_msg "$_PROJECT_NAME installation and configuration completed"
}

configure
