#!/bin/sh

# Copyright (c) 2016 Open Baton (http://www.openbaton.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


##########################
#### General Settings ####
##########################

set -e
set -u
#set -x # only for DEBUG

# Make available the functions defined in /lib/lsb/init-functions
. /lib/lsb/init-functions


##########################
#### Global Variables ####
##########################

OPENBATON_COMPONENT_NAME_FANCY="Network Slicing Engine (NSE)"
OPENBATON_COMPONENT_NAME=nse
OPENBATON_COMPONENT_RELATIVE_SUBPATH=nse

OPENBATON_COMPONENT_CONFIG_FILE=/etc/openbaton/openbaton-${OPENBATON_COMPONENT_NAME}.properties
OPENBATON_COMPONENT_JAR_FILE_NAME=openbaton-${OPENBATON_COMPONENT_NAME}
OPENBATON_COMPONENT_JAR_INSTALL_DIR=/usr/lib/openbaton/${OPENBATON_COMPONENT_RELATIVE_SUBPATH}

OPENBATON_COMPONENT_PID_FILE=/var/run/openbaton-${OPENBATON_COMPONENT_NAME}.pid
DAEMON_USER=root
OSTYPE=$(uname)



_USER="$(id -un 2>/dev/null || true)"

_ex='sh -c'

checkBinary () {
  if command -v $1 >/dev/null 2>&1 ; then
      log_success_msg "Checking for '$1'"
      return 0
  else
      log_failure_msg "Checking for '$1'"
      return 1
  fi
}

if [ "$_USER" != 'root' ]; then
    if checkBinary sudo; then
        _ex='sudo -E sh -c'
    elif checkBinary su; then
        _ex='su -c'
    fi
fi


####################
#### Open Baton ####
####################

check_already_running () {
    instance=$(ps aux | grep -v grep | grep "${OPENBATON_COMPONENT_JAR_FILE_NAME}" | grep "jar" | wc -l)
    if [ ${instance} -ne 0 ]; then
        log_warning_msg "The Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} is already running"
        exit 1
    fi
}

set_jar_version () {
    openbaton_component_jar_file_name_versioned=$(ls -ct ${OPENBATON_COMPONENT_JAR_INSTALL_DIR} | grep "${OPENBATON_COMPONENT_JAR_FILE_NAME}" | grep "jar" | head -n 1)
    if [ ${openbaton_component_jar_file_name_versioned} = "" ]; then
        log_failure_msg "The Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} is not installed (jar-file not found)"
        exit 1
    fi
}

configure () {
    check_already_running
    set_jar_version
}

start () {
    configure
    log_success_msg "Starting the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} .."
    start-stop-daemon --start --background --pidfile ${OPENBATON_COMPONENT_PID_FILE} --make-pidfile --user ${DAEMON_USER} --chuid ${DAEMON_USER} --exec /usr/bin/java -- -jar ${OPENBATON_COMPONENT_JAR_INSTALL_DIR}/${openbaton_component_jar_file_name_versioned} --spring.config.location=file:${OPENBATON_COMPONENT_CONFIG_FILE}
    #log_end_msg $?
}

stop () {
    log_success_msg "Stopping the Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} .."
    start-stop-daemon --stop --pidfile ${OPENBATON_COMPONENT_PID_FILE}
    #log_end_msg $?
}

kill () {
    kill -9 $(cat "${OPENBATON_COMPONENT_PID_FILE}")
    #log_end_msg $?
}

restart () {
    stop
    start
}

usage () {
    echo "Open Baton ${OPENBATON_COMPONENT_NAME_FANCY}"
    #echo "Usage:\n\t [openbaton-${OPENBATON_COMPONENT_NAME} start|stop|restart] | [service openbaton-${OPENBATON_COMPONENT_NAME} start|stop|restart] | [start|stop openbaton-${OPENBATON_COMPONENT_NAME}] | [systemctl start|stop openbaton-${OPENBATON_COMPONENT_NAME}.service]"
    echo "Usage:\n\t [openbaton-${OPENBATON_COMPONENT_NAME} start|stop|restart|kill] | [service openbaton-${OPENBATON_COMPONENT_NAME} start|stop|restart|kill] | [start|stop|restart|kill openbaton-${OPENBATON_COMPONENT_NAME}]"
}


##
#   MAIN
##

if [ ${#} -eq 0 ]; then
    usage
    exit 1
fi

for cmd in ${@}
do
    case ${cmd} in
        "start" )
            start ;;
        "stop" )
            stop ;;
        "restart" )
            restart ;;
        "kill" )
            kill ;;
         *)
	        usage;;
    esac
    if [ ${?} -ne 0 ]; then
	    exit 1
    fi
done
